#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <limits>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::fixed;
using std::string;
using std::copy;
using std::sort;
using std::numeric_limits;
using std::streamsize;
